#!/usr/bin/env bash
# Bakes the HDR viewer's shaders (src/app/shaders/*.vert, *.frag) with Qt's qsb into src/app/shaders/HdrShaders.inc,
# so building Montage needs no shader tools. Run after changing a shader:
#   scripts/bake-hdr-shaders.sh /path/to/Qt/6.x/bin/qsb
# The .qsb format is Qt 6.5's (loaded by every later Qt): SPIR-V, GLSL ES 100 / 120 / 150, HLSL 5.0 and MSL 1.2.
set -euo pipefail
qsb="${1:-qsb}"
dir="$(cd "$(dirname "$0")/../src/app/shaders" && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
out="$dir/HdrShaders.inc"
{
  echo "// Generated by scripts/bake-hdr-shaders.sh from src/app/shaders; do not edit."
  for f in hdrview.vert hdrpicture.frag hdroverlay.frag; do
    LC_ALL=C.UTF-8 "$qsb" --qt6 --qsbversion 65 -o "$tmp/$f.qsb" "$dir/$f"
    name="k$(echo "$f" | sed -E 's/^hdr//; s/\.(vert|frag)$/_\1/; s/(^|_)([a-z])/\U\2/g')Qsb"
    echo "static const unsigned char ${name}[] = {"
    od -An -v -tx1 "$tmp/$f.qsb" | sed -E 's/ ([0-9a-f]{2})/0x\1,/g; s/^/   /'
    echo "};"
  done
} > "$out"
echo "wrote $out"
