#!/usr/bin/env python3
"""Generates src/core/AafMetaDictionary.inc: the AAF MetaDictionary (the
class and type definitions of the AAF object model) as pyaaf2 (MIT) writes
it, which Montage's AAF writer copies into every file it makes.

    python3 -m pip install pyaaf2==1.7.1
    python3 scripts/gen-aaf-metadict.py src/core/AafMetaDictionary.inc

The data is a zlib stream (Qt's qUncompress layout: a 4-byte big-endian
length first) of entries in pre-order under /MetaDictionary-1:
  u8 type (1 storage, 2 stream), u16 path length, UTF-8 path relative to the
  MetaDictionary, then a storage's 16-byte CLSID or a stream's u32 length and bytes.
"""
import io, os, struct, sys, tempfile, zlib
import aaf2
import aaf2.cfb as cfb

out = sys.argv[1]
tmp = os.path.join(tempfile.mkdtemp(), "empty.aaf")
with aaf2.open(tmp, "w") as f:
    pass
c = cfb.CompoundFileBinary(open(tmp, "rb"))
root = c.find("/MetaDictionary-1")
buf = io.BytesIO()
count = 0

def emit(entry, rel):
    global count
    path = rel.encode("utf-8")
    if entry.isdir():
        buf.write(struct.pack("<BH", 1, len(path)) + path + entry.class_id.bytes_le)
        count += 1
        for child in sorted(c.listdir(entry), key=lambda e: e.name):
            emit(child, (rel + "/" if rel else "") + child.name)
    else:
        data = c.open(entry.path()).read()
        buf.write(struct.pack("<BH", 2, len(path)) + path + struct.pack("<I", len(data)) + data)
        count += 1

emit(root, "")
raw = buf.getvalue()
packed = struct.pack(">I", len(raw)) + zlib.compress(raw, 9)
with open(out, "w") as o:
    o.write("// Generated by scripts/gen-aaf-metadict.py from pyaaf2 %s (MIT): the AAF MetaDictionary.\n"
            % getattr(aaf2, "__version__", "1.7.1"))
    o.write("// %d entries, %d bytes (%d compressed). Do not edit.\n" % (count, len(raw), len(packed)))
    o.write("static const unsigned char kAafMetaDictionary[] = {\n")
    for i in range(0, len(packed), 24):
        o.write("    " + ", ".join("0x%02x" % b for b in packed[i:i + 24]) + ",\n")
    o.write("};\n")
print(count, len(raw), len(packed))
